### ISSUE TITLE
fix(symbolon): KeyringCredentialProvider is pub(crate) but re-exported pub

### ISSUE THREAD

**Issue by forkwright** [forkwright/aletheia#3046]
## Bug

`cargo check --workspace --all-features` fails because `KeyringCredentialProvider` is declared `pub(crate)` but re-exported as `pub` from `crates/symbolon/src/credential/mod.rs`.

```
error[E0365]: `KeyringCredentialProvider` is only public within the crate, and cannot be re-exported outside
  --> crates/symbolon/src/credential/mod.rs:19:9
```

Introduced by #2225 (full audit lint fix).

## Fix

The type is used from `crates/aletheia/src/commands/credential.rs` and `crates/aletheia/src/runtime.rs` — it must be `pub`. Change `pub(crate) struct KeyringCredentialProvider` → `pub struct KeyringCredentialProvider` and the `new()` ctor similarly.

## Impact

Blocks `cargo check --workspace --all-features` and any refactor that requires that gate (e.g., #2800 env::var consolidation).
